// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

#include "fuzzing/test.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr rsp_msg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : rsp_status_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR rsp_msg::rsp_msg(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct rsp_msgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR rsp_msgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~rsp_msgDefaultTypeInternal() {}
  union {
    rsp_msg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 rsp_msgDefaultTypeInternal _rsp_msg_default_instance_;

inline constexpr req_msg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : req_command_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR req_msg::req_msg(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct req_msgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR req_msgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~req_msgDefaultTypeInternal() {}
  union {
    req_msg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 req_msgDefaultTypeInternal _req_msg_default_instance_;

inline constexpr mmio_output::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        addr_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR mmio_output::mmio_output(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct mmio_outputDefaultTypeInternal {
  PROTOBUF_CONSTEXPR mmio_outputDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~mmio_outputDefaultTypeInternal() {}
  union {
    mmio_output _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 mmio_outputDefaultTypeInternal _mmio_output_default_instance_;

inline constexpr mmio_input::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        length_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR mmio_input::mmio_input(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct mmio_inputDefaultTypeInternal {
  PROTOBUF_CONSTEXPR mmio_inputDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~mmio_inputDefaultTypeInternal() {}
  union {
    mmio_input _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 mmio_inputDefaultTypeInternal _mmio_input_default_instance_;

inline constexpr mmio_addr_range::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : lo_addr_{::int64_t{0}},
        hi_addr_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR mmio_addr_range::mmio_addr_range(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct mmio_addr_rangeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR mmio_addr_rangeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~mmio_addr_rangeDefaultTypeInternal() {}
  union {
    mmio_addr_range _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 mmio_addr_rangeDefaultTypeInternal _mmio_addr_range_default_instance_;

inline constexpr basic_block::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : pc_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR basic_block::basic_block(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct basic_blockDefaultTypeInternal {
  PROTOBUF_CONSTEXPR basic_blockDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~basic_blockDefaultTypeInternal() {}
  union {
    basic_block _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 basic_blockDefaultTypeInternal _basic_block_default_instance_;
static ::_pb::Metadata file_level_metadata_test_2eproto[6];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_test_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_test_2eproto = nullptr;
const ::uint32_t TableStruct_test_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::req_msg, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::req_msg, _impl_.req_command_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::rsp_msg, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::rsp_msg, _impl_.rsp_status_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::mmio_input, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::mmio_input, _impl_.value_),
    PROTOBUF_FIELD_OFFSET(::mmio_input, _impl_.length_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::mmio_output, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::mmio_output, _impl_.value_),
    PROTOBUF_FIELD_OFFSET(::mmio_output, _impl_.addr_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::basic_block, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::basic_block, _impl_.pc_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::mmio_addr_range, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::mmio_addr_range, _impl_.lo_addr_),
    PROTOBUF_FIELD_OFFSET(::mmio_addr_range, _impl_.hi_addr_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::req_msg)},
        {9, -1, -1, sizeof(::rsp_msg)},
        {18, -1, -1, sizeof(::mmio_input)},
        {28, -1, -1, sizeof(::mmio_output)},
        {38, -1, -1, sizeof(::basic_block)},
        {47, -1, -1, sizeof(::mmio_addr_range)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::_req_msg_default_instance_._instance,
    &::_rsp_msg_default_instance_._instance,
    &::_mmio_input_default_instance_._instance,
    &::_mmio_output_default_instance_._instance,
    &::_basic_block_default_instance_._instance,
    &::_mmio_addr_range_default_instance_._instance,
};
const char descriptor_table_protodef_test_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\ntest.proto\"\036\n\007req_msg\022\023\n\013req_command\030\001"
    " \001(\t\"\035\n\007rsp_msg\022\022\n\nrsp_status\030\001 \001(\005\"+\n\nm"
    "mio_input\022\r\n\005value\030\001 \001(\014\022\016\n\006length\030\002 \001(\005"
    "\"*\n\013mmio_output\022\r\n\005value\030\001 \001(\014\022\014\n\004addr\030\002"
    " \001(\003\"\031\n\013basic_block\022\n\n\002pc\030\001 \001(\014\"3\n\017mmio_"
    "addr_range\022\017\n\007lo_addr\030\001 \001(\003\022\017\n\007hi_addr\030\002"
    " \001(\0032\300\002\n\013TestService\022%\n\rHandleCommand\022\010."
    "req_msg\032\010.rsp_msg\"\000\022&\n\016set_breakpoint\022\010."
    "req_msg\032\010.rsp_msg\"\000\022)\n\021remove_breakpoint"
    "\022\010.req_msg\032\010.rsp_msg\"\000\0223\n\023MMIO_set_addr_"
    "range\022\020.mmio_addr_range\032\010.rsp_msg\"\000\022)\n\rg"
    "et_MMIOvalue\022\010.req_msg\032\014.mmio_output\"\000\022("
    "\n\rset_MMIOvalue\022\013.mmio_input\032\010.rsp_msg\"\000"
    "\022-\n\021get_code_coverage\022\010.req_msg\032\014.basic_"
    "block\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_test_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_test_2eproto = {
    false,
    false,
    575,
    descriptor_table_protodef_test_2eproto,
    "test.proto",
    &descriptor_table_test_2eproto_once,
    nullptr,
    0,
    6,
    schemas,
    file_default_instances,
    TableStruct_test_2eproto::offsets,
    file_level_metadata_test_2eproto,
    file_level_enum_descriptors_test_2eproto,
    file_level_service_descriptors_test_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_test_2eproto_getter() {
  return &descriptor_table_test_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_test_2eproto(&descriptor_table_test_2eproto);
// ===================================================================

class req_msg::_Internal {
 public:
};

req_msg::req_msg(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:req_msg)
}
inline PROTOBUF_NDEBUG_INLINE req_msg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : req_command_(arena, from.req_command_),
        _cached_size_{0} {}

req_msg::req_msg(
    ::google::protobuf::Arena* arena,
    const req_msg& from)
    : ::google::protobuf::Message(arena) {
  req_msg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:req_msg)
}
inline PROTOBUF_NDEBUG_INLINE req_msg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : req_command_(arena),
        _cached_size_{0} {}

inline void req_msg::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
req_msg::~req_msg() {
  // @@protoc_insertion_point(destructor:req_msg)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void req_msg::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.req_command_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void req_msg::Clear() {
// @@protoc_insertion_point(message_clear_start:req_msg)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.req_command_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* req_msg::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 27, 2> req_msg::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_req_msg_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string req_command = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(req_msg, _impl_.req_command_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string req_command = 1;
    {PROTOBUF_FIELD_OFFSET(req_msg, _impl_.req_command_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\7\13\0\0\0\0\0\0"
    "req_msg"
    "req_command"
  }},
};

::uint8_t* req_msg::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:req_msg)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string req_command = 1;
  if (!this->_internal_req_command().empty()) {
    const std::string& _s = this->_internal_req_command();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "req_msg.req_command");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:req_msg)
  return target;
}

::size_t req_msg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:req_msg)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string req_command = 1;
  if (!this->_internal_req_command().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_req_command());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData req_msg::_class_data_ = {
    req_msg::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* req_msg::GetClassData() const {
  return &_class_data_;
}

void req_msg::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<req_msg*>(&to_msg);
  auto& from = static_cast<const req_msg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:req_msg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_req_command().empty()) {
    _this->_internal_set_req_command(from._internal_req_command());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void req_msg::CopyFrom(const req_msg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:req_msg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool req_msg::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* req_msg::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void req_msg::InternalSwap(req_msg* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.req_command_, &other->_impl_.req_command_, arena);
}

::google::protobuf::Metadata req_msg::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_test_2eproto_getter, &descriptor_table_test_2eproto_once,
      file_level_metadata_test_2eproto[0]);
}
// ===================================================================

class rsp_msg::_Internal {
 public:
};

rsp_msg::rsp_msg(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rsp_msg)
}
rsp_msg::rsp_msg(
    ::google::protobuf::Arena* arena, const rsp_msg& from)
    : rsp_msg(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE rsp_msg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void rsp_msg::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.rsp_status_ = {};
}
rsp_msg::~rsp_msg() {
  // @@protoc_insertion_point(destructor:rsp_msg)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void rsp_msg::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void rsp_msg::Clear() {
// @@protoc_insertion_point(message_clear_start:rsp_msg)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.rsp_status_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* rsp_msg::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> rsp_msg::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_rsp_msg_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int32 rsp_status = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(rsp_msg, _impl_.rsp_status_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(rsp_msg, _impl_.rsp_status_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 rsp_status = 1;
    {PROTOBUF_FIELD_OFFSET(rsp_msg, _impl_.rsp_status_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* rsp_msg::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rsp_msg)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 rsp_status = 1;
  if (this->_internal_rsp_status() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_rsp_status(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rsp_msg)
  return target;
}

::size_t rsp_msg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rsp_msg)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 rsp_status = 1;
  if (this->_internal_rsp_status() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_rsp_status());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData rsp_msg::_class_data_ = {
    rsp_msg::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* rsp_msg::GetClassData() const {
  return &_class_data_;
}

void rsp_msg::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<rsp_msg*>(&to_msg);
  auto& from = static_cast<const rsp_msg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rsp_msg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_rsp_status() != 0) {
    _this->_internal_set_rsp_status(from._internal_rsp_status());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void rsp_msg::CopyFrom(const rsp_msg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rsp_msg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool rsp_msg::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* rsp_msg::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void rsp_msg::InternalSwap(rsp_msg* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.rsp_status_, other->_impl_.rsp_status_);
}

::google::protobuf::Metadata rsp_msg::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_test_2eproto_getter, &descriptor_table_test_2eproto_once,
      file_level_metadata_test_2eproto[1]);
}
// ===================================================================

class mmio_input::_Internal {
 public:
};

mmio_input::mmio_input(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mmio_input)
}
inline PROTOBUF_NDEBUG_INLINE mmio_input::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : value_(arena, from.value_),
        _cached_size_{0} {}

mmio_input::mmio_input(
    ::google::protobuf::Arena* arena,
    const mmio_input& from)
    : ::google::protobuf::Message(arena) {
  mmio_input* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.length_ = from._impl_.length_;

  // @@protoc_insertion_point(copy_constructor:mmio_input)
}
inline PROTOBUF_NDEBUG_INLINE mmio_input::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : value_(arena),
        _cached_size_{0} {}

inline void mmio_input::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.length_ = {};
}
mmio_input::~mmio_input() {
  // @@protoc_insertion_point(destructor:mmio_input)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void mmio_input::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.value_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void mmio_input::Clear() {
// @@protoc_insertion_point(message_clear_start:mmio_input)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_.ClearToEmpty();
  _impl_.length_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* mmio_input::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> mmio_input::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_mmio_input_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int32 length = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(mmio_input, _impl_.length_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(mmio_input, _impl_.length_)}},
    // bytes value = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(mmio_input, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes value = 1;
    {PROTOBUF_FIELD_OFFSET(mmio_input, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // int32 length = 2;
    {PROTOBUF_FIELD_OFFSET(mmio_input, _impl_.length_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* mmio_input::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mmio_input)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bytes value = 1;
  if (!this->_internal_value().empty()) {
    const std::string& _s = this->_internal_value();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  // int32 length = 2;
  if (this->_internal_length() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_length(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mmio_input)
  return target;
}

::size_t mmio_input::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mmio_input)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes value = 1;
  if (!this->_internal_value().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_value());
  }

  // int32 length = 2;
  if (this->_internal_length() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_length());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData mmio_input::_class_data_ = {
    mmio_input::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* mmio_input::GetClassData() const {
  return &_class_data_;
}

void mmio_input::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<mmio_input*>(&to_msg);
  auto& from = static_cast<const mmio_input&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mmio_input)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_value().empty()) {
    _this->_internal_set_value(from._internal_value());
  }
  if (from._internal_length() != 0) {
    _this->_internal_set_length(from._internal_length());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void mmio_input::CopyFrom(const mmio_input& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mmio_input)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool mmio_input::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* mmio_input::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void mmio_input::InternalSwap(mmio_input* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
        swap(_impl_.length_, other->_impl_.length_);
}

::google::protobuf::Metadata mmio_input::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_test_2eproto_getter, &descriptor_table_test_2eproto_once,
      file_level_metadata_test_2eproto[2]);
}
// ===================================================================

class mmio_output::_Internal {
 public:
};

mmio_output::mmio_output(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mmio_output)
}
inline PROTOBUF_NDEBUG_INLINE mmio_output::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : value_(arena, from.value_),
        _cached_size_{0} {}

mmio_output::mmio_output(
    ::google::protobuf::Arena* arena,
    const mmio_output& from)
    : ::google::protobuf::Message(arena) {
  mmio_output* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.addr_ = from._impl_.addr_;

  // @@protoc_insertion_point(copy_constructor:mmio_output)
}
inline PROTOBUF_NDEBUG_INLINE mmio_output::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : value_(arena),
        _cached_size_{0} {}

inline void mmio_output::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.addr_ = {};
}
mmio_output::~mmio_output() {
  // @@protoc_insertion_point(destructor:mmio_output)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void mmio_output::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.value_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void mmio_output::Clear() {
// @@protoc_insertion_point(message_clear_start:mmio_output)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_.ClearToEmpty();
  _impl_.addr_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* mmio_output::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> mmio_output::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_mmio_output_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int64 addr = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(mmio_output, _impl_.addr_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(mmio_output, _impl_.addr_)}},
    // bytes value = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(mmio_output, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes value = 1;
    {PROTOBUF_FIELD_OFFSET(mmio_output, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // int64 addr = 2;
    {PROTOBUF_FIELD_OFFSET(mmio_output, _impl_.addr_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* mmio_output::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mmio_output)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bytes value = 1;
  if (!this->_internal_value().empty()) {
    const std::string& _s = this->_internal_value();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  // int64 addr = 2;
  if (this->_internal_addr() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<2>(
            stream, this->_internal_addr(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mmio_output)
  return target;
}

::size_t mmio_output::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mmio_output)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes value = 1;
  if (!this->_internal_value().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_value());
  }

  // int64 addr = 2;
  if (this->_internal_addr() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_addr());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData mmio_output::_class_data_ = {
    mmio_output::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* mmio_output::GetClassData() const {
  return &_class_data_;
}

void mmio_output::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<mmio_output*>(&to_msg);
  auto& from = static_cast<const mmio_output&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mmio_output)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_value().empty()) {
    _this->_internal_set_value(from._internal_value());
  }
  if (from._internal_addr() != 0) {
    _this->_internal_set_addr(from._internal_addr());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void mmio_output::CopyFrom(const mmio_output& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mmio_output)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool mmio_output::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* mmio_output::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void mmio_output::InternalSwap(mmio_output* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
        swap(_impl_.addr_, other->_impl_.addr_);
}

::google::protobuf::Metadata mmio_output::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_test_2eproto_getter, &descriptor_table_test_2eproto_once,
      file_level_metadata_test_2eproto[3]);
}
// ===================================================================

class basic_block::_Internal {
 public:
};

basic_block::basic_block(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:basic_block)
}
inline PROTOBUF_NDEBUG_INLINE basic_block::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : pc_(arena, from.pc_),
        _cached_size_{0} {}

basic_block::basic_block(
    ::google::protobuf::Arena* arena,
    const basic_block& from)
    : ::google::protobuf::Message(arena) {
  basic_block* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:basic_block)
}
inline PROTOBUF_NDEBUG_INLINE basic_block::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : pc_(arena),
        _cached_size_{0} {}

inline void basic_block::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
basic_block::~basic_block() {
  // @@protoc_insertion_point(destructor:basic_block)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void basic_block::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.pc_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void basic_block::Clear() {
// @@protoc_insertion_point(message_clear_start:basic_block)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pc_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* basic_block::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> basic_block::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_basic_block_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bytes pc = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(basic_block, _impl_.pc_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes pc = 1;
    {PROTOBUF_FIELD_OFFSET(basic_block, _impl_.pc_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* basic_block::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:basic_block)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bytes pc = 1;
  if (!this->_internal_pc().empty()) {
    const std::string& _s = this->_internal_pc();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:basic_block)
  return target;
}

::size_t basic_block::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:basic_block)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes pc = 1;
  if (!this->_internal_pc().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_pc());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData basic_block::_class_data_ = {
    basic_block::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* basic_block::GetClassData() const {
  return &_class_data_;
}

void basic_block::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<basic_block*>(&to_msg);
  auto& from = static_cast<const basic_block&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:basic_block)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_pc().empty()) {
    _this->_internal_set_pc(from._internal_pc());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void basic_block::CopyFrom(const basic_block& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:basic_block)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool basic_block::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* basic_block::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void basic_block::InternalSwap(basic_block* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pc_, &other->_impl_.pc_, arena);
}

::google::protobuf::Metadata basic_block::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_test_2eproto_getter, &descriptor_table_test_2eproto_once,
      file_level_metadata_test_2eproto[4]);
}
// ===================================================================

class mmio_addr_range::_Internal {
 public:
};

mmio_addr_range::mmio_addr_range(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mmio_addr_range)
}
mmio_addr_range::mmio_addr_range(
    ::google::protobuf::Arena* arena, const mmio_addr_range& from)
    : mmio_addr_range(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE mmio_addr_range::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void mmio_addr_range::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, lo_addr_),
           0,
           offsetof(Impl_, hi_addr_) -
               offsetof(Impl_, lo_addr_) +
               sizeof(Impl_::hi_addr_));
}
mmio_addr_range::~mmio_addr_range() {
  // @@protoc_insertion_point(destructor:mmio_addr_range)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void mmio_addr_range::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void mmio_addr_range::Clear() {
// @@protoc_insertion_point(message_clear_start:mmio_addr_range)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.lo_addr_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.hi_addr_) -
      reinterpret_cast<char*>(&_impl_.lo_addr_)) + sizeof(_impl_.hi_addr_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* mmio_addr_range::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> mmio_addr_range::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_mmio_addr_range_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int64 hi_addr = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(mmio_addr_range, _impl_.hi_addr_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(mmio_addr_range, _impl_.hi_addr_)}},
    // int64 lo_addr = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(mmio_addr_range, _impl_.lo_addr_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(mmio_addr_range, _impl_.lo_addr_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 lo_addr = 1;
    {PROTOBUF_FIELD_OFFSET(mmio_addr_range, _impl_.lo_addr_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // int64 hi_addr = 2;
    {PROTOBUF_FIELD_OFFSET(mmio_addr_range, _impl_.hi_addr_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* mmio_addr_range::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mmio_addr_range)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 lo_addr = 1;
  if (this->_internal_lo_addr() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_lo_addr(), target);
  }

  // int64 hi_addr = 2;
  if (this->_internal_hi_addr() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<2>(
            stream, this->_internal_hi_addr(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mmio_addr_range)
  return target;
}

::size_t mmio_addr_range::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mmio_addr_range)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 lo_addr = 1;
  if (this->_internal_lo_addr() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_lo_addr());
  }

  // int64 hi_addr = 2;
  if (this->_internal_hi_addr() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_hi_addr());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData mmio_addr_range::_class_data_ = {
    mmio_addr_range::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* mmio_addr_range::GetClassData() const {
  return &_class_data_;
}

void mmio_addr_range::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<mmio_addr_range*>(&to_msg);
  auto& from = static_cast<const mmio_addr_range&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mmio_addr_range)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_lo_addr() != 0) {
    _this->_internal_set_lo_addr(from._internal_lo_addr());
  }
  if (from._internal_hi_addr() != 0) {
    _this->_internal_set_hi_addr(from._internal_hi_addr());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void mmio_addr_range::CopyFrom(const mmio_addr_range& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mmio_addr_range)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool mmio_addr_range::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* mmio_addr_range::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void mmio_addr_range::InternalSwap(mmio_addr_range* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(mmio_addr_range, _impl_.hi_addr_)
      + sizeof(mmio_addr_range::_impl_.hi_addr_)
      - PROTOBUF_FIELD_OFFSET(mmio_addr_range, _impl_.lo_addr_)>(
          reinterpret_cast<char*>(&_impl_.lo_addr_),
          reinterpret_cast<char*>(&other->_impl_.lo_addr_));
}

::google::protobuf::Metadata mmio_addr_range::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_test_2eproto_getter, &descriptor_table_test_2eproto_once,
      file_level_metadata_test_2eproto[5]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
