name: lint

on:
  push:
    branches: [ master, dev** ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  TARGET_ARCH: linux64

jobs:
  lint:
    name: lint
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup Dependencies
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libelf-dev libsdl2-dev libvncserver-dev libslirp-dev clang-tidy

    - name: Patch unicorn
      run: |
        git apply ${{github.workspace}}/patches/unicorn-*.patch
      working-directory: ${{github.workspace}}/deps/ocx-qemu-arm/unicorn

    - name: Configure
      run: |
        cmake \
          -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
          -DAVP64_BUILD_TESTS=ON \
          -DOCX_QEMU_ARM_BUILD_TESTS=OFF \
          -DAVP64_LINTER="clang-tidy" \
          -DCMAKE_CXX_STANDARD=17

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j $(nproc)
