name: style

on:
  push:
    branches: [ master, dev** ]
  pull_request:
    branches: [ master ]

jobs:
  style:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Check code style
      run: deps/vcml/utils/format -n

